package fonttheater.models

object FontLibrary2 {

  val featuredGoogleWebFontsSansSerifHeadings = new FontCollection2(
    "featuredGoogleWebFontsSansSerifHeadings",
    new Font2("Montserrat", GoogleWebFonts(null)),
    new Font2("Ropa Sans", GoogleWebFonts(null)),
    new Font2("Telex", GoogleWebFonts(null)),
    new Font2("Questrial", GoogleWebFonts(null)),
    new Font2("Imprima", GoogleWebFonts(null)),
    new Font2("Ruda", GoogleWebFonts(null)),
    new Font2("Signika Negative", GoogleWebFonts(null)),
    new Font2("Signika", GoogleWebFonts(null)),
    new Font2("Oxygen", GoogleWebFonts(null)),
    new Font2("Voces", GoogleWebFonts(null)),
    new Font2("Share", GoogleWebFonts(null)),
    new Font2("Coda", GoogleWebFonts(null)),
    new Font2("Varela Round", GoogleWebFonts(null)),
    new Font2("Abel", GoogleWebFonts(null)),
    new Font2("Mako", GoogleWebFonts(null)),
    new Font2("Michroma", GoogleWebFonts(null), letterSpacingFactor = 1),
    new Font2("Duru Sans", GoogleWebFonts(null)),
    new Font2("Magra", GoogleWebFonts(null)),
    new Font2("Exo", GoogleWebFonts(null)),
    new Font2("Asap", GoogleWebFonts(null)),
    new Font2("Muli", GoogleWebFonts(null)),
    new Font2("Francois One", GoogleWebFonts(null)),
    new Font2("Actor", GoogleWebFonts(null)),
    new Font2("Basic", GoogleWebFonts(null)),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)),
    new Font2("Carme", GoogleWebFonts(null)),
    new Font2("Play", GoogleWebFonts(null))
    //new Font2("Rosario", 		GoogleWebFonts(null)),
    //new Font2("Overlock", 		GoogleWebFonts(null)),
    //new Font2("Contrail One", 		GoogleWebFonts(null)),
    //new Font2("Gruppo", 		GoogleWebFonts(null)),
    //new Font2("Dosis", 		GoogleWebFonts(null)),
    //new Font2("Economica", 	GoogleWebFonts(null)),
    //new Font2("Marvel", 		GoogleWebFonts(null)),
    //new Font2("Molengo", 		GoogleWebFonts(null)),
  );

  val featuredGoogleWebFontsSlabSerifHeadings = new FontCollection2(
    "featuredGoogleWebFontsSlabSerifHeadings",
    new Font2("Poly", GoogleWebFonts(null)),
    new Font2("Quando", GoogleWebFonts(null)),
    new Font2("Rokkitt", GoogleWebFonts(null)),
    new Font2("Bitter", GoogleWebFonts(null)),
    new Font2("Average", GoogleWebFonts(null)),
    new Font2("Belgrano", GoogleWebFonts(null)),
    new Font2("Patua One", GoogleWebFonts(null)),
    new Font2("Habibi", GoogleWebFonts(null)),
    new Font2("Merriweather", GoogleWebFonts(null)),
    new Font2("Kreon", GoogleWebFonts(null)),
    new Font2("Crete Round", GoogleWebFonts(null)),
    new Font2("Amethysta", GoogleWebFonts(null)),
    new Font2("Trykker", GoogleWebFonts(null)),
    new Font2("Vollkorn", GoogleWebFonts(null)),
    new Font2("Brawler", GoogleWebFonts(null)),
    new Font2("Headland One", GoogleWebFonts(null)),
    new Font2("Neuton", GoogleWebFonts(null), letterSpacingFactor = 0.5),
    new Font2("Coustard", GoogleWebFonts(null)),
    new Font2("Petrona", GoogleWebFonts(null)),
    new Font2("Corben", GoogleWebFonts(null)),
    new Font2("Copse", GoogleWebFonts(null)),
    new Font2("Droid Serif", GoogleWebFonts(null)),
    new Font2("Enriqueta", GoogleWebFonts(null)),
    new Font2("Andada", GoogleWebFonts(null)),
    new Font2("Bree Serif", GoogleWebFonts(null)),
    new Font2("Cutive", GoogleWebFonts(null)),
    new Font2("Fjord One", GoogleWebFonts(null))
    //new Font2("Crimson Text", 		GoogleWebFonts(null)),
    //new Font2("Mate", 		GoogleWebFonts(null)),
    //new Font2("Antic Slab", 		GoogleWebFonts(null)),
    //new Font2("Tienne", 		GoogleWebFonts(null)),
    //new Font2("Kotta One", 		GoogleWebFonts(null)),
    //new Font2("Arvo", 		GoogleWebFonts(null)),
    //new Font2("Port Lligat Slab", 		GoogleWebFonts(null)),
    //new Font2("Esteban", 		GoogleWebFonts(null)),
    //new Font2("Noticia Text", 		GoogleWebFonts(null)),
  );

  val fontFaceFonts = new FontCollection2(
    "fontfacefonts",
    new Font2("jaf-bernina-sans-condensed", "JAF Bernina Sans Condensed", CssFontFace(null)),
    new Font2("jaf-bernina-sans-narrow-light", "JAF Bernina Sans Narrow Light", CssFontFace(null)),
    new Font2("parisine-std", CssFontFace(null)),
    new Font2("Rokkitt-webfont", "Rokkkitt", FontFace("/font-face-kit/rokkitt-fontfacekit")),
    new Font2("Poly-Regular-webfont", "Poly", FontFace("/font-face-kit/poly-fontfacekit")),
    new Font2("SofiaProLight-webfont", "Sofia Pro Light", FontFace("/font-face-kit/sofia-pro-fontfacekit")),
    new Font2("Metrophobic-webfont", "Metrophobic", FontFace("/font-face-kit/metrophobic-fontfacekit")),
    new Font2("FrancoisOne-webfont", "Francois One", FontFace("/font-face-kit/francois-one-fontfacekit")),
    new Font2("Bevan-webfont", "Bevan", FontFace("/font-face-kit/bevan-fontfacekit")),
    new Font2("Michroma-webfont", "Michroma", FontFace("/font-face-kit/michroma-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("BPreplay-webfont", "BPreplay", FontFace("/font-face-kit/BPreplay-fontfacekit")),
    new Font2("Signika-Light-webfont", "Signika Light", FontFace("/font-face-kit/signika-fontfacekit")),
    new Font2("Signika-Regular-webfont", "Signika", FontFace("/font-face-kit/signika-fontfacekit")),
    new Font2("Signika-Semibold-webfont", "Signika Semibold", FontFace("/font-face-kit/signika-fontfacekit")),
    new Font2("Signika-Bold-webfont", "Signika Bold", FontFace("/font-face-kit/signika-fontfacekit")),
    new Font2("GandhiSans-Regular-webfont", "Gandhi Sans", FontFace("/font-face-kit/gandhi-sans-fontfacekit")),
    new Font2("ColabReg-webfont", "Colaborate", FontFace("/font-face-kit/colaborate-fontfacekit")),
    new Font2("CallunaSansRegular-webfont", "Calluna", FontFace("/font-face-kit/calluna-fontfacekit")),
    new Font2("mentone-semibol-webfont", "Mentone Semibold", FontFace("/font-face-kit/mentone-fontfacekit")),
    //new Font2("YanoneKaffeesatz-Thin-webfont",		"Yanone Kaffeesatz Thin",			FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit")),
    new Font2("YanoneKaffeesatz-Light-webfont", "Yanone Kaffeesatz Light", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit")),
    new Font2("YanoneKaffeesatz-Regular-webfont", "Yanone Kaffeesatz", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("YanoneKaffeesatz-Bold-webfont", "Yanone Kaffeesatz Bold", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit"), letterSpacingFactor = 1),
    new Font2("Vollkorn-Regular-webfont", "Vollkorn", FontFace("/font-face-kit/vollkorn-fontfacekit")),
    new Font2("Vollkorn-Bold-webfont", "Vollkorn Bold", FontFace("/font-face-kit/vollkorn-fontfacekit")),
    new Font2("Bitter-Regular-webfont", "Bitter", FontFace("/font-face-kit/bitter-fontfacekit")),
    new Font2("Bitter-Bold-webfont", "Bitter Bold", FontFace("/font-face-kit/bitter-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("RopaSans-Regular-webfont", "Ropa Sans", FontFace("/font-face-kit/ropa-sans-fontfacekit")),
    new Font2("questrial-regular-webfont", "Questrial", FontFace("/font-face-kit/questrial-fontfacekit")),
    new Font2("mako-regular-webfont", "Mako", FontFace("/font-face-kit/mako-fontfacekit")),
    new Font2("Cantarell-Regular-webfont", "Cantarell", FontFace("/font-face-kit/cantarell-fontfacekit")),
    new Font2("Cantarell-Bold-webfont", "Cantarell Bold", FontFace("/font-face-kit/cantarell-fontfacekit")),
    new Font2("Cabin-Regular-webfont", "Cabin", FontFace("/font-face-kit/cabin-fontfacekit")),
    new Font2("Cabin-Medium-webfont", "Cabin Medium", FontFace("/font-face-kit/cabin-fontfacekit")),
    new Font2("Cabin-SemiBold-webfont", "Cabin Sembold", FontFace("/font-face-kit/cabin-fontfacekit")),
    new Font2("Cabin-Bold-webfont", "Cabin Bold", FontFace("/font-face-kit/cabin-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("OpenSans-Light-webfont", "Open Sans Light", FontFace("/font-face-kit/open-sans-fontfacekit")),
    new Font2("OpenSans-Regular-webfont", "Open Sans", FontFace("/font-face-kit/open-sans-fontfacekit")),
    new Font2("OpenSans-SemiBold-webfont", "Open Sans Semibold", FontFace("/font-face-kit/open-sans-fontfacekit")),
    new Font2("OpenSans-Bold-webfont", "Open Sans Bold", FontFace("/font-face-kit/open-sans-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("OpenSans-ExtraBold-webfont", "Open Sans Extra Bold", FontFace("/font-face-kit/open-sans-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("PTN57F-webfont", "PT Sans Narrow", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("PTN77F-webfont", "PT Sans Narrow Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("PTC55F-webfont", "PT Sans Caption", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("PTC75F-webfont", "PT Sans Caption Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("PTS55F-webfont", "PT Sans", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("PTS75F-webfont", "PT Sans Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("PTS56F-webfont", "PT Sans Italic", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("PTS76F-webfont", "PT Sans Bold Italic", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
    new Font2("Candal-webfont", "Candal", FontFace("/font-face-kit/candal-fontfacekit")),
    new Font2("Oxygen-webfont", "Oxygen", FontFace("/font-face-kit/oxygen-fontfacekit")),
    new Font2("Oxygen-Bold-webfont", "Oxygen Bold", FontFace("/font-face-kit/oxygen-fontfacekit"), letterSpacingFactor = 0.5),
    new Font2("Roboto-Thin-webfont", "Roboto Thin", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-Light-webfont", "Roboto Light", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-Regular-webfont", "Roboto", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-Medium-webfont", "Roboto Medium", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-Bold-webfont", "Roboto Bold", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-Black-webfont", "Roboto Black", FontFace("/font-face-kit/roboto-fontfacekit"), letterSpacingFactor = 1),
    new Font2("Roboto-Condensed-webfont", "Roboto Condensed", FontFace("/font-face-kit/roboto-fontfacekit")),
    new Font2("Roboto-BoldCondensed-webfont", "Roboto Bold Condensed", FontFace("/font-face-kit/roboto-fontfacekit"), letterSpacingFactor = 1),
    new Font2("SourceSansPro-ExtraLight-webfont", "Source Sans Pro - Extra Light", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("SourceSansPro-Light-webfont", "Source Sans Pro - Light", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("SourceSansPro-Regular-webfont", "Source Sans Pro", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("SourceSansPro-SemiBold-webfont", "Source Sans Pro - Semibold", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("SourceSansPro-Bold-webfont", "Source Sans Pro - Bold", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("SourceSansPro-Black-webfont", "Source Sans Pro - Black", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
    new Font2("Oswald-Regular-webfont", "Oswald", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
    new Font2("Oswald-Light-webfont", "Oswald Light", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
    new Font2("Oswald-Bold-webfont", "Oswald Bold", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
    new Font2("Amble-Light-Webfont", "Amble Light", FontFace("/font-face-kit/amble-fontfacekit")),
    new Font2("Amble-LightCondensed-Webfont", "Amble Light Condensed", FontFace("/font-face-kit/amble-fontfacekit")),
    new Font2("Amble-Regular-Webfont", "Amble", FontFace("/font-face-kit/amble-fontfacekit")),
    new Font2("urbano", FontFace(null)),
    new Font2("urbano-light-webfont", FontFace(null)),
    new Font2("urbano-lightcond-webfont", FontFace(null)),
    new Font2("urbano-regular-webfont", FontFace(null)),
    new Font2("vafle_classic-webfont", FontFace(null))
  );


  val standardFonts = new FontCollection2(
    "standardfonts",
    new Font2("Arial", ClientOsInstalled()),
    new Font2("Arial Black", ClientOsInstalled()),
    new Font2("Verdana", ClientOsInstalled()),
    new Font2("Lucida Sans Unicode", ClientOsInstalled()),
    new Font2("Lucida Console", ClientOsInstalled()),
    new Font2("Trebuchet MS", ClientOsInstalled()),
    new Font2("Tahoma", ClientOsInstalled()),
    new Font2("Times New Roman", ClientOsInstalled()),
    new Font2("Georgia", ClientOsInstalled()),
    new Font2("Palatino Linotype", ClientOsInstalled()),
    new Font2("Courier New", ClientOsInstalled()),
    new Font2("Courier", ClientOsInstalled())
  );

  val installedFonts = new FontCollection2(
    "installedfonts",
    new Font2("Urbano Light", ClientOsInstalled()),
    new Font2("Urbano", ClientOsInstalled()),
    new Font2("Urbano Black", ClientOsInstalled()),
    new Font2("Urbano Ultra", ClientOsInstalled()),
    new Font2("Urbano Lt Ext Cond", ClientOsInstalled()),
    new Font2("Urbano Ext Cond", ClientOsInstalled()),
    new Font2("Urbano Lt Cond", ClientOsInstalled()),
    new Font2("Urbano Cond", ClientOsInstalled()),
    new Font2("Urbano ExBd Cond", ClientOsInstalled()),
    new Font2("Urbano Exp", ClientOsInstalled()),
    new Font2("Urbano ExBd Exp", ClientOsInstalled()),
    new Font2("Urbano Blk Exp", ClientOsInstalled()),
    new Font2("Hoefler Text", ClientOsInstalled()),
    new Font2("Liberation Sans Narrow", ClientOsInstalled())
  );

  val fontsDotComFonts = new FontCollection2(
    "fontsdotcomfonts",
    new Font2("HelveticaNeueW01-57Cn", FontsDotCom(null)),
    new Font2("HelveticaNeueW01-ThinCn 673383", FontsDotCom(null)),
    new Font2("DIN Next W02 Cond", FontsDotCom(null)),
    new Font2("TradeGothicNextW01-Heav 693241", FontsDotCom(null)),
    new Font2("EurostileNextW01-Regula", FontsDotCom(null)),
    new Font2("FrutigerNeueW01-Regular", FontsDotCom(null))
  );

  val cufonFonts = new FontCollection2(
    "cufonfonts",
    new Font2("Open Sans", "Open Sans Condensed", Cufon("/cufon-fonts/Open_Sans_300.font.js")),
    new Font2("Bebas Neue", Cufon("/cufon-fonts/bebas-neue.cufonfonts.js"), letterSpacingFactor = 1),
    new Font2("League Gothic", Cufon("/cufon-fonts/league-gothic.cufonfonts.js"), letterSpacingFactor = 0.5),
    new Font2("DIN Condensed Normal", Cufon("/cufon-fonts/DIN_Condensed_Normal_400.font.js"), letterSpacingFactor = 1),
    new Font2("Enigmatic Regular", Cufon("/cufon-fonts/enigmatic.cufonfonts.js"), letterSpacingFactor = 1),
    new Font2("Gnuolane Free", Cufon("/cufon-fonts/gnuolane.cufonfonts.js"), letterSpacingFactor = 0.5),
    new Font2("Steelfish-Regular", Cufon("/cufon-fonts/steelfish.cufonfonts.js"), letterSpacingFactor = 0.7),
    new Font2("WinterthurCondensed", Cufon("/cufon-fonts/winterthurcondensed.cufonfonts.js"), letterSpacingFactor = 0.5),
    new Font2("Zag Regular", Cufon("/cufon-fonts/zag.cufonfonts.js"), letterSpacingFactor = 0.5),
    new Font2("Source Sans Pro", Cufon("/cufon-fonts/Source_Sans_Pro_400.font.js")),
    new Font2("Amble", Cufon("/cufon-fonts/amble_400.font.js")),
    new Font2("Amble-Light", Cufon("/cufon-fonts/amble-light_300.font.js")),
    new Font2("Amble-Light-Condensed", Cufon("/cufon-fonts/amble-light-condensed_300.font.js")),
    new Font2("Cantarell Regular", Cufon("/cufon-fonts/cantarell.cufonfonts.js")),
    new Font2("CartoGothic Std Book", Cufon("/cufon-fonts/cartogothic-std.cufonfonts.js")),
    new Font2("ExpresswayRg-Regular", Cufon("/cufon-fonts/expressway.cufonfonts.js")),
    new Font2("Helvetica Neue", Cufon("/cufon-fonts/Helvetica_Neue_400-Helvetica_Neue_700-Helvetica_Neue_italic_400-Helvetica_Neue_italic_700.font.js")),
    new Font2("Mentone SemiBold", Cufon("/cufon-fonts/mentone.cufonfonts.js")),
    new Font2("Myriad Pro Regular", Cufon("/cufon-fonts/myriad-pro.cufonfonts.js")),
    new Font2("PT Sans", Cufon("/cufon-fonts/pt-sans.cufonfonts.js")),
    new Font2("Urbano", Cufon("/cufon-fonts/Urbano_400-Urbano_700-Urbano_italic_400-Urbano_italic_700.font.js")),
    new Font2("Urbano Condensed", Cufon("/cufon-fonts/Urbano_Cond_400-Urbano_Cond_700-Urbano_Cond_italic_400-Urbano_Cond_italic_700.font.js")),
    new Font2("Urbano Extra Condensed", Cufon("/cufon-fonts/Urbano_Cond_400-Urbano_Cond_700-Urbano_Cond_italic_400-Urbano_Cond_italic_700.font_2.js")),
    new Font2("XXX", Cufon("/cufon-fonts/Urbano_Extra_Cond_400-Urbano_Extra_Cond_800-Urbano_Extra_Cond_400-Urbano_Extra_Cond_italic_800.font.js")),
    new Font2("XXX", Cufon("/cufon-fonts/Urbano_Light_300-Urbano_Light_300-Urbano_Light_italic_300-Urbano_Light_italic_300.font.js")),
    new Font2("XXX", Cufon("/cufon-fonts/Urbano_Light_400-Urbano_Light_800-Urbano_Light_400-Urbano_Light_italic_800.font.js")),
    new Font2("XXX", Cufon("/cufon-fonts/Urbano_Light_Cond_300-Urbano_Light_Cond_300-Urbano_Light_Cond_italic_300-Urbano_Light_Cond_italic_300.font.js"))
  );


  val googleWebFonts = new FontCollection2(
    "googlewebfonts",
    new Font2("Allerta Stencil", GoogleWebFonts(null)), //, TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Anonymous Pro", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Buda", "", 300,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Candal", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_HEAVY),
    new Font2("Cantarell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Coda", "", 800,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    //		new Font2("Coda Caption", "", 800,	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_HEAVY),
    new Font2("Cousine", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Didact Gothic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans Mono", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Francois One", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
    new Font2("Inconsolata", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    //		new Font2("Josefin Sans", "Ultra-Light", 100, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    //		new Font2("Josefin Sans", "Book", 300,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    new Font2("Josefin Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    //		new Font2("Josefin Sans", "Semi-Bold", 600,		GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    //		new Font2("Josefin Sans", "Bold", 700,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    new Font2("Jura", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    //		new Font2("Jura", "Medium", 500, 				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    //		new Font2("Jura", "Semi-Bold", 600,				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Lato:light", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT, TAG_WEIGHT_THIN),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Lekton", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Michroma", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Open Sans Condensed", "Book", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
    //		new Font2("Open Sans Condensed", "Bold", 700,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
    new Font2("Orbitron", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Oswald", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Puritan", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    //		new Font2("Raleway", "", 100,		GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Terminal Dosis Light", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Wire One", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
    //		new Font2("Yanone Kaffeesatz", "Light", 200, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
    //		new Font2("Yanone Kaffeesatz", "Book", 300, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
    new Font2("Yanone Kaffeesatz", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED)
  );

  val normalTextFonts = new FontCollection2(
    "normalSansSerifTextFonts",
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cantarell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Didact Gothic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Open Sans Condensed", "Book", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Puritan", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
  );

  val goodSerifNormalTextFonts = new FontCollection2(
    "goodSerifNormalTextFonts",
    new Font2("Cambria", ClientOsInstalled())
  );


  val goodNormalTextFonts11Px = new FontCollection2(
    "goodNormalTextFonts11Px",
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Lucida Sans Unicode", ClientOsInstalled()),
    new Font2("Arial", ClientOsInstalled())
  );

  val goodNormalTextFonts12Px = new FontCollection2(
    "goodNormalTextFonts12Px",
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Lucida Sans Unicode", ClientOsInstalled()),
    new Font2("Arial", ClientOsInstalled())
  );

  val goodNormalTextFonts13Px = new FontCollection2(
    "goodNormalTextFonts13Px",
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ratio", CssFontFace(null)),
    new Font2("Arial", ClientOsInstalled())
  );


  val goodNormalTextFonts14Px = new FontCollection2(
    "goodNormalTextFonts14Px",
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Consolas", ClientOsInstalled()),
    new Font2("Georgia", ClientOsInstalled()),
    new Font2("Constantia", ClientOsInstalled()),
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Cantarell", 				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ratio", CssFontFace(null)),
    new Font2("Arial", ClientOsInstalled())
  );

  val goodNormalTextFonts15Px = new FontCollection2(
    "goodNormalTextFonts15Px",
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ratio", CssFontFace(null)),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Arial", ClientOsInstalled())
  );

  val goodNormalTextFonts16Px = new FontCollection2(
    "goodNormalTextFonts16Px",
    new Font2("Calibri", ClientOsInstalled()),
    new Font2("Segoe UI", ClientOsInstalled()),
    new Font2("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Microsoft Sans Serif", ClientOsInstalled()),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    new Font2("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
    new Font2("Ratio", CssFontFace(null)),
    new Font2("Corbel", ClientOsInstalled()),
    new Font2("Candara", ClientOsInstalled()),
    new Font2("Arial", ClientOsInstalled())
  );


  val googleWebFontsSerifOrSlabSerif = new FontCollection2(
    "googlewebfontsseriforslabserif",
    new Font2("Arvo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Bentham", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Brawler", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Cardo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Copse", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Crimson Text", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Droid Serif", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("EB Garamond", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Goudy Bookletter 1911", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("IM Fell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Josefin Slab", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Judson", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Kameron", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Kreon", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Lora", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Merriweather", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Neuton", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("OFL Sorts Mill Goudy TT", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Old Standard TT", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Podkova", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("PT Serif", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Playfair Display", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Quattrocento", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Rokkitt", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
    new Font2("Tinos", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
    new Font2("Vollkorn", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SERIF_FONT)
  );

  val cssFontFaceFonts = new FontCollection2(
    "cssFontFaceFonts",
    new Font2("elena-web-basic", CssFontFace(null)),
    new Font2("urbano", CssFontFace("urbano_400_normal.css")),
    new Font2("sanchez", CssFontFace("sanchez_400_normal.css")),
    new Font2("atrament-web", CssFontFace(null)),
    new Font2("atrament-web_light", CssFontFace(null)),
    new Font2("etica", CssFontFace(null)),
    new Font2("nudista-web", CssFontFace(null)),
    new Font2("obliqua", CssFontFace(null)),
    new Font2("ronnia-condensed", CssFontFace(null)),
    new Font2("alternate-gothic-no-3-d", CssFontFace(null)),
    new Font2("franklin-gothic-comp-urw", CssFontFace(null)),
    new Font2("franklin-gothic-ext-comp-urw", CssFontFace(null)),
    new Font2("ratio-display", CssFontFace(null)),
    new Font2("runda", CssFontFace(null)),
    new Font2("ronnia", CssFontFace(null)),
    new Font2("prenton-condensed", CssFontFace(null)),
    new Font2("comenia-sans-web", CssFontFace(null)),
    new Font2("katarine-web", CssFontFace(null)),
    new Font2("adelle", CssFontFace(null)),
    new Font2("republic-web-condensed", CssFontFace(null)),
    new Font2("crete-rounded-web", CssFontFace(null)),
    new Font2("league-gothic", CssFontFace(null)),
    new Font2("bebas-neue", CssFontFace(null)),
    new Font2("vinyl", CssFontFace(null)),
    new Font2("p22-underground-pc", CssFontFace(null)),
    new Font2("gnuolane", CssFontFace(null)),
    new Font2("allumi-std-extended", CssFontFace(null)),
    new Font2("etica-display", CssFontFace(null)),
    new Font2("sommet", CssFontFace(null)),
    new Font2("t26-carbon", CssFontFace(null)),
    new Font2("purista-web", CssFontFace(null)),
    new Font2("sirba-web", CssFontFace(null)),
    new Font2("apolline", CssFontFace(null)),
    new Font2("lemonde-journal", CssFontFace(null))
  );

  val typekitGoodWindowsRenderingSansSerifs = new FontCollection2(
    "typekitgoodwindowsrenderingsansserifs",
    new Font2("Source Sans Pro", GoogleWebFonts(null)),
    new Font2("adelle-sans", CssFontFace(null)),
    new Font2("etica", CssFontFace(null)),
    new Font2("nudista-web", CssFontFace(null)),
    new Font2("obliqua", CssFontFace(null)),
    new Font2("runda", CssFontFace(null)),
    new Font2("ronnia", CssFontFace(null)),
    new Font2("ronnia-condensed", CssFontFace(null)),
    new Font2("prenton-condensed", CssFontFace(null)),
    new Font2("parisine-std", CssFontFace(null)),
    new Font2("comenia-sans-web", CssFontFace(null)),
    new Font2("katarine-web", CssFontFace(null)),
    new Font2("calluna-sans", CssFontFace(null)),
    new Font2("ratio-display", CssFontFace(null)),
    new Font2("gnuolane", CssFontFace(null)),

    new Font2("quara-web", CssFontFace(null)),
    new Font2("tilden-sans-light", CssFontFace(null)),
    new Font2("allumi-std", CssFontFace(null)),
    new Font2("allumi-std-extended", CssFontFace(null)),
    new Font2("cronos-pro-display", CssFontFace(null)),


    new Font2("museo-sans-rounded", CssFontFace(null)),

    new Font2("franklin-gothic-comp-urw", CssFontFace(null)),
    new Font2("franklin-gothic-ext-comp-urw", CssFontFace(null)),
    new Font2("alternate-gothic-no-1-d", CssFontFace(null)),
    new Font2("alternate-gothic-no-2-d", CssFontFace(null)),
    new Font2("alternate-gothic-no-3-d", CssFontFace(null)),
    new Font2("league-gothic", CssFontFace(null)),
    new Font2("bebas-neue", CssFontFace(null)),


    new Font2("etica-display", CssFontFace(null)),
    new Font2("sommet", CssFontFace(null)),
    new Font2("t26-carbon", CssFontFace(null)),

    new Font2("p22-underground-pc", CssFontFace(null)),
    new Font2("soleil", CssFontFace(null)),

    new Font2("tablet-gothic-wide", CssFontFace(null)),
    new Font2("tablet-gothic", CssFontFace(null)),
    new Font2("tablet-gothic-narrow", CssFontFace(null)),
    new Font2("tablet-gothic-semi-condensed", CssFontFace(null)),
    new Font2("tablet-gothic-condensed", CssFontFace(null)),
    new Font2("tablet-gothic-compressed", CssFontFace(null)),

    new Font2("atrament-web", CssFontFace(null)),
    new Font2("purista-web", CssFontFace(null)),
    new Font2("vinyl", CssFontFace(null))


  );

  val typekitBestRenderingSansSerifs20Px = new FontCollection2(
    "typekitBestRenderingSansSerifs20Px",

    new Font2("adelle-sans", CssFontFace(null)),
    new Font2("museo-sans-rounded", CssFontFace(null)),
    new Font2("tablet-gothic-condensed", CssFontFace(null)),
    new Font2("alternate-gothic-no-3-d", CssFontFace(null)),
    new Font2("soleil", CssFontFace(null)),
    new Font2("purista-web", CssFontFace(null)),
    new Font2("etica", CssFontFace(null)),
    new Font2("nudista-web", CssFontFace(null)),
    new Font2("obliqua", CssFontFace(null)),
    new Font2("runda", CssFontFace(null)),
    new Font2("ronnia", CssFontFace(null)),
    new Font2("ronnia-condensed", CssFontFace(null)),
    new Font2("parisine-std", CssFontFace(null)),
    new Font2("comenia-sans-web", CssFontFace(null)),
    new Font2("katarine-web", CssFontFace(null)),
    new Font2("calluna-sans", CssFontFace(null)),

    new Font2("quara-web", CssFontFace(null)),
    new Font2("allumi-std", CssFontFace(null)),
    new Font2("allumi-std-extended", CssFontFace(null)),
    new Font2("cronos-pro-display", CssFontFace(null)),


    new Font2("franklin-gothic-comp-urw", CssFontFace(null)),


    new Font2("bebas-neue", CssFontFace(null)),

    new Font2("sommet", CssFontFace(null)),
    new Font2("t26-carbon", CssFontFace(null)),


    new Font2("tablet-gothic-wide", CssFontFace(null)),
    new Font2("tablet-gothic", CssFontFace(null)),
    new Font2("tablet-gothic-semi-condensed", CssFontFace(null)),

    new Font2("tablet-gothic-compressed", CssFontFace(null))


  );

  val typekitGoodWindowsRenderingSerifs = new FontCollection2(
    "typekitgoodwindowsrenderingserifs",
    new Font2("adelle", CssFontFace(null)),
    new Font2("republic-web-condensed", CssFontFace(null)),
    new Font2("crete-rounded-web", CssFontFace(null)),
    new Font2("sirba-web", CssFontFace(null)),
    new Font2("apolline", CssFontFace(null)),
    new Font2("bree-serif", CssFontFace(null)),
    new Font2("lemonde-journal", CssFontFace(null))
  );


  val dinAlternatives = new FontCollection2(
    "dinAlternatives",
    new Font2("DIN Next W02 Cond", FontsDotCom(null)),
    new Font2("atrament-web", CssFontFace(null)),
    new Font2("nudista-web", CssFontFace(null)),
    new Font2("purista-web", CssFontFace(null))
  );

  val helveticaAlternatives = new FontCollection2(
    "helveticaAlternatives",
    new Font2("HelveticaNeueW01-57Cn", FontsDotCom(null)),
    new Font2("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
    //		new Font2("Open Sans Condensed", "Light", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
    new Font2("etica", CssFontFace(null)),
    new Font2("nudista-web", CssFontFace(null)),
    new Font2("ratio-display", CssFontFace(null)),
    new Font2("runda", CssFontFace(null)),
    new Font2("ronnia", CssFontFace(null)),
    new Font2("comenia-sans-web", CssFontFace(null)),
    new Font2("katarine-web", CssFontFace(null))
  );

}