#import(fonttheater.models._)


#{
	val fontLibrary = new FontLibrary {

	  val newFeaturedGoogleWebFonts = new FontCollection(
	    "newFeaturedGoogleWebFonts",
        new Font("Gilda Display", GoogleWebFonts(null)),
        new Font("Convergence", GoogleWebFonts(null)),
        new Font("Anaheim", GoogleWebFonts(null)),
        new Font("Rambla", GoogleWebFonts(null)),
        new Font("Libre Baskerville", GoogleWebFonts(null)),
        new Font("Orienta", GoogleWebFonts(null)),
        new Font("Headland One", GoogleWebFonts(null)),
        new Font("Armata", GoogleWebFonts(null)),
        new Font("Average Sans", GoogleWebFonts(null)),
        new Font("Glegoo", GoogleWebFonts(null)),
        new Font("ABeeZee", GoogleWebFonts(null)),
        new Font("Domine", GoogleWebFonts(null)),
        new Font("Imprima", GoogleWebFonts(null)),
        new Font("Capriola", GoogleWebFonts(null)),
        new Font("Julius Sans One", GoogleWebFonts(null)),
        new Font("Fjalla One", GoogleWebFonts(null)),
        new Font("Roboto", GoogleWebFonts(null)),
        new Font("Donegal One", GoogleWebFonts(null)),
        new Font("Gafata", GoogleWebFonts(null)),
        new Font("Cinzel", GoogleWebFonts(null)),
        new Font("Roboto Condensed", GoogleWebFonts(null)),
        new Font("Pontano Sans", GoogleWebFonts(null))
      );
	  
	  val featuredGoogleWebFontsSansSerifHeadings = new FontCollection(
	    "featuredGoogleWebFontsSansSerifHeadings",
	    new Font("Montserrat", GoogleWebFonts(null)),
	    new Font("Ropa Sans", GoogleWebFonts(null)),
	    new Font("Telex", GoogleWebFonts(null)),
	    new Font("Questrial", GoogleWebFonts(null)),
	    new Font("Imprima", GoogleWebFonts(null)),
	    new Font("Ruda", GoogleWebFonts(null)),
	    new Font("Signika Negative", GoogleWebFonts(null)),
	    new Font("Signika", GoogleWebFonts(null)),
	    new Font("Oxygen", GoogleWebFonts(null)),
	    new Font("Voces", GoogleWebFonts(null)),
	    new Font("Share", GoogleWebFonts(null)),
	    new Font("Coda", GoogleWebFonts(null)),
	    new Font("Varela Round", GoogleWebFonts(null)),
	    new Font("Abel", GoogleWebFonts(null)),
	    new Font("Mako", GoogleWebFonts(null)),
	    new Font("Michroma", GoogleWebFonts(null), letterSpacingFactor = 1),
	    new Font("Duru Sans", GoogleWebFonts(null)),
	    new Font("Magra", GoogleWebFonts(null)),
	    new Font("Exo", GoogleWebFonts(null)),
	    new Font("Asap", GoogleWebFonts(null)),
	    new Font("Muli", GoogleWebFonts(null)),
	    new Font("Francois One", GoogleWebFonts(null)),
	    new Font("Actor", GoogleWebFonts(null)),
	    new Font("Basic", GoogleWebFonts(null)),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)),
	    new Font("Carme", GoogleWebFonts(null)),
	    new Font("Play", GoogleWebFonts(null))
	    //new Font2("Rosario", 		GoogleWebFonts(null)),
	    //new Font2("Overlock", 		GoogleWebFonts(null)),
	    //new Font2("Contrail One", 		GoogleWebFonts(null)),
	    //new Font2("Gruppo", 		GoogleWebFonts(null)),
	    //new Font2("Dosis", 		GoogleWebFonts(null)),
	    //new Font2("Economica", 	GoogleWebFonts(null)),
	    //new Font2("Marvel", 		GoogleWebFonts(null)),
	    //new Font2("Molengo", 		GoogleWebFonts(null)),
	  );

	  val featuredGoogleWebFontsSlabSerifHeadings = new FontCollection(
	    "featuredGoogleWebFontsSlabSerifHeadings",
	    new Font("Poly", GoogleWebFonts(null)),
	    new Font("Quando", GoogleWebFonts(null)),
	    new Font("Rokkitt", GoogleWebFonts(null)),
	    new Font("Bitter", GoogleWebFonts(null)),
	    new Font("Average", GoogleWebFonts(null)),
	    new Font("Belgrano", GoogleWebFonts(null)),
	    new Font("Patua One", GoogleWebFonts(null)),
	    new Font("Habibi", GoogleWebFonts(null)),
	    new Font("Merriweather", GoogleWebFonts(null)),
	    new Font("Kreon", GoogleWebFonts(null)),
	    new Font("Crete Round", GoogleWebFonts(null)),
	    new Font("Amethysta", GoogleWebFonts(null)),
	    new Font("Trykker", GoogleWebFonts(null)),
	    new Font("Vollkorn", GoogleWebFonts(null)),
	    new Font("Brawler", GoogleWebFonts(null)),
	    new Font("Headland One", GoogleWebFonts(null)),
	    new Font("Neuton", GoogleWebFonts(null), letterSpacingFactor = 0.5),
	    new Font("Coustard", GoogleWebFonts(null)),
	    new Font("Petrona", GoogleWebFonts(null)),
	    new Font("Corben", GoogleWebFonts(null)),
	    new Font("Copse", GoogleWebFonts(null)),
	    new Font("Droid Serif", GoogleWebFonts(null)),
	    new Font("Enriqueta", GoogleWebFonts(null)),
	    new Font("Andada", GoogleWebFonts(null)),
	    new Font("Bree Serif", GoogleWebFonts(null)),
	    new Font("Cutive", GoogleWebFonts(null)),
	    new Font("Fjord One", GoogleWebFonts(null))
	    //new Font2("Crimson Text", 		GoogleWebFonts(null)),
	    //new Font2("Mate", 		GoogleWebFonts(null)),
	    //new Font2("Antic Slab", 		GoogleWebFonts(null)),
	    //new Font2("Tienne", 		GoogleWebFonts(null)),
	    //new Font2("Kotta One", 		GoogleWebFonts(null)),
	    //new Font2("Arvo", 		GoogleWebFonts(null)),
	    //new Font2("Port Lligat Slab", 		GoogleWebFonts(null)),
	    //new Font2("Esteban", 		GoogleWebFonts(null)),
	    //new Font2("Noticia Text", 		GoogleWebFonts(null)),
	  );

	  val geometricSansSerifCircularFonts = new FontCollection(
	    "geometricSansSerifCircularFonts",
	    new Font("MuseoSans_500-webfont", "Museo Sans 500", FontFace("/font-face-kit/museo-sans-fontfacekit")),
	    new Font("questrial-regular-webfont", "Questrial", FontFace("/font-face-kit/questrial-fontfacekit")),
	    new Font("Montserrat", GoogleWebFonts(null)),
	    new Font("soleil", CssFontFace(null)),
	    new Font("SofiaProLight-webfont", "Sofia Pro Light", FontFace("/font-face-kit/sofia-pro-fontfacekit"))
      );

	  val fontFaceFonts = new FontCollection(
	    "fontfacefonts",
	    new Font("MuseoSans_500-webfont", "Museo Sans 500", FontFace("/font-face-kit/museo-sans-fontfacekit")),
	    new Font("SofiaProLiCond-webfont", "Sofia Pro Condensed Light", FontFace("/font-face-kit/sofia-pro-condensed-fontfacekit")),
	    new Font("parisine-std", CssFontFace(null)),
	    new Font("jaf-bernina-sans-condensed", "JAF Bernina Sans Condensed", CssFontFace(null)),
	    new Font("jaf-bernina-sans-narrow-light", "JAF Bernina Sans Narrow Light", CssFontFace(null)),	    
	    new Font("Rokkitt-webfont", "Rokkkitt", FontFace("/font-face-kit/rokkitt-fontfacekit")),
	    new Font("Poly-Regular-webfont", "Poly", FontFace("/font-face-kit/poly-fontfacekit")),
	    new Font("SofiaProLight-webfont", "Sofia Pro Light", FontFace("/font-face-kit/sofia-pro-fontfacekit")),
	    new Font("Metrophobic-webfont", "Metrophobic", FontFace("/font-face-kit/metrophobic-fontfacekit")),
	    new Font("FrancoisOne-webfont", "Francois One", FontFace("/font-face-kit/francois-one-fontfacekit")),
	    new Font("Bevan-webfont", "Bevan", FontFace("/font-face-kit/bevan-fontfacekit")),
	    new Font("Michroma-webfont", "Michroma", FontFace("/font-face-kit/michroma-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("BPreplay-webfont", "BPreplay", FontFace("/font-face-kit/BPreplay-fontfacekit")),
	    new Font("Signika-Light-webfont", "Signika Light", FontFace("/font-face-kit/signika-fontfacekit")),
	    new Font("Signika-Regular-webfont", "Signika", FontFace("/font-face-kit/signika-fontfacekit")),
	    new Font("Signika-Semibold-webfont", "Signika Semibold", FontFace("/font-face-kit/signika-fontfacekit")),
	    new Font("Signika-Bold-webfont", "Signika Bold", FontFace("/font-face-kit/signika-fontfacekit")),
	    new Font("GandhiSans-Regular-webfont", "Gandhi Sans", FontFace("/font-face-kit/gandhi-sans-fontfacekit")),
	    new Font("ColabReg-webfont", "Colaborate", FontFace("/font-face-kit/colaborate-fontfacekit")),
	    new Font("CallunaSansRegular-webfont", "Calluna", FontFace("/font-face-kit/calluna-fontfacekit")),
	    new Font("mentone-semibol-webfont", "Mentone Semibold", FontFace("/font-face-kit/mentone-fontfacekit")),
	    //new Font2("YanoneKaffeesatz-Thin-webfont",		"Yanone Kaffeesatz Thin",			FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit")),
	    new Font("YanoneKaffeesatz-Light-webfont", "Yanone Kaffeesatz Light", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit")),
	    new Font("YanoneKaffeesatz-Regular-webfont", "Yanone Kaffeesatz", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("YanoneKaffeesatz-Bold-webfont", "Yanone Kaffeesatz Bold", FontFace("/font-face-kit/Yanone-Kaffeesatz-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Vollkorn-Regular-webfont", "Vollkorn", FontFace("/font-face-kit/Vollkorn-fontfacekit")),
	    new Font("Vollkorn-Bold-webfont", "Vollkorn Bold", FontFace("/font-face-kit/Vollkorn-fontfacekit")),
	    new Font("Bitter-Regular-webfont", "Bitter", FontFace("/font-face-kit/bitter-fontfacekit")),
	    new Font("Bitter-Bold-webfont", "Bitter Bold", FontFace("/font-face-kit/bitter-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("RopaSans-Regular-webfont", "Ropa Sans", FontFace("/font-face-kit/ropa-sans-fontfacekit")),
	    new Font("questrial-regular-webfont", "Questrial", FontFace("/font-face-kit/questrial-fontfacekit")),
	    new Font("mako-regular-webfont", "Mako", FontFace("/font-face-kit/mako-fontfacekit")),
	    new Font("Cantarell-Regular-webfont", "Cantarell", FontFace("/font-face-kit/Cantarell-fontfacekit")),
	    new Font("Cantarell-Bold-webfont", "Cantarell Bold", FontFace("/font-face-kit/Cantarell-fontfacekit")),
	    new Font("Cabin-Regular-webfont", "Cabin", FontFace("/font-face-kit/cabin-fontfacekit")),
	    new Font("Cabin-Medium-webfont", "Cabin Medium", FontFace("/font-face-kit/cabin-fontfacekit")),
	    new Font("Cabin-SemiBold-webfont", "Cabin Semibold", FontFace("/font-face-kit/cabin-fontfacekit")),
	    new Font("Cabin-Bold-webfont", "Cabin Bold", FontFace("/font-face-kit/cabin-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("OpenSans-Light-webfont", "Open Sans Light", FontFace("/font-face-kit/open-sans-fontfacekit")),
	    new Font("OpenSans-Regular-webfont", "Open Sans", FontFace("/font-face-kit/open-sans-fontfacekit")),
	    new Font("OpenSans-Semibold-webfont", "Open Sans Semibold", FontFace("/font-face-kit/open-sans-fontfacekit")),
	    new Font("OpenSans-Bold-webfont", "Open Sans Bold", FontFace("/font-face-kit/open-sans-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("OpenSans-ExtraBold-webfont", "Open Sans Extra Bold", FontFace("/font-face-kit/open-sans-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("PTN57F-webfont", "PT Sans Narrow", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("PTN77F-webfont", "PT Sans Narrow Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("PTC55F-webfont", "PT Sans Caption", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("PTC75F-webfont", "PT Sans Caption Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("PTS55F-webfont", "PT Sans", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("PTS75F-webfont", "PT Sans Bold", FontFace("/font-face-kit/PT-Sans-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("PTS56F-webfont", "PT Sans Italic", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("PTS76F-webfont", "PT Sans Bold Italic", FontFace("/font-face-kit/PT-Sans-fontfacekit")),
	    new Font("Candal-webfont", "Candal", FontFace("/font-face-kit/candal-fontfacekit")),
	    new Font("Oxygen-webfont", "Oxygen", FontFace("/font-face-kit/oxygen-fontfacekit")),
	    new Font("Oxygen-Bold-webfont", "Oxygen Bold", FontFace("/font-face-kit/oxygen-fontfacekit"), letterSpacingFactor = 0.5),
	    new Font("Roboto-Thin-webfont", "Roboto Thin", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-Light-webfont", "Roboto Light", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-Regular-webfont", "Roboto", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-Medium-webfont", "Roboto Medium", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-Bold-webfont", "Roboto Bold", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-Black-webfont", "Roboto Black", FontFace("/font-face-kit/roboto-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Roboto-Condensed-webfont", "Roboto Condensed", FontFace("/font-face-kit/roboto-fontfacekit")),
	    new Font("Roboto-BoldCondensed-webfont", "Roboto Bold Condensed", FontFace("/font-face-kit/roboto-fontfacekit"), letterSpacingFactor = 1),
	    new Font("SourceSansPro-ExtraLight-webfont", "Source Sans Pro - Extra Light", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("SourceSansPro-Light-webfont", "Source Sans Pro - Light", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("SourceSansPro-Regular-webfont", "Source Sans Pro", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("SourceSansPro-Semibold-webfont", "Source Sans Pro - Semibold", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("SourceSansPro-Bold-webfont", "Source Sans Pro - Bold", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("SourceSansPro-Black-webfont", "Source Sans Pro - Black", FontFace("/font-face-kit/source-sans-pro-fontfacekit")),
	    new Font("Oswald-Regular-webfont", "Oswald", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Oswald-Light-webfont", "Oswald Light", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Oswald-Bold-webfont", "Oswald Bold", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Amble-Light-webfont", "Amble Light", FontFace("/font-face-kit/Amble-Light-fontfacekit")),
	    new Font("Amble-LightCondensed-webfont", "Amble Light Condensed", FontFace("/font-face-kit/amble-fontfacekit")),
	    new Font("Amble-Regular-webfont", "Amble", FontFace("/font-face-kit/amble-fontfacekit")),
	    new Font("urbano", FontFace(null)),
	    new Font("urbano-light-webfont", FontFace(null)),
	    new Font("urbano-lightcond-webfont", FontFace(null)),
	    new Font("urbano-regular-webfont", FontFace(null)),
	    new Font("vafle_classic-webfont", FontFace(null))
	  );


	  val standardFonts = new FontCollection(
	    "standardfonts",
	    new Font("Arial", ClientOsInstalled()),
	    new Font("Arial Black", ClientOsInstalled()),
	    new Font("Verdana", ClientOsInstalled()),
	    new Font("Lucida Sans Unicode", ClientOsInstalled()),
	    new Font("Lucida Console", ClientOsInstalled()),
	    new Font("Trebuchet MS", ClientOsInstalled()),
	    new Font("Tahoma", ClientOsInstalled()),
	    new Font("Times New Roman", ClientOsInstalled()),
	    new Font("Georgia", ClientOsInstalled()),
	    new Font("Palatino Linotype", ClientOsInstalled()),
	    new Font("Courier New", ClientOsInstalled()),
	    new Font("Courier", ClientOsInstalled())
	  );

	  val installedFonts = new FontCollection(
	    "installedfonts",
	    new Font("Urbano Light", ClientOsInstalled()),
	    new Font("Urbano", ClientOsInstalled()),
	    new Font("Urbano Black", ClientOsInstalled()),
	    new Font("Urbano Ultra", ClientOsInstalled()),
	    new Font("Urbano Lt Ext Cond", ClientOsInstalled()),
	    new Font("Urbano Ext Cond", ClientOsInstalled()),
	    new Font("Urbano Lt Cond", ClientOsInstalled()),
	    new Font("Urbano Cond", ClientOsInstalled()),
	    new Font("Urbano ExBd Cond", ClientOsInstalled()),
	    new Font("Urbano Exp", ClientOsInstalled()),
	    new Font("Urbano ExBd Exp", ClientOsInstalled()),
	    new Font("Urbano Blk Exp", ClientOsInstalled()),
	    new Font("Hoefler Text", ClientOsInstalled()),
	    new Font("Liberation Sans Narrow", ClientOsInstalled())
	  );

	  val fontsDotComFonts = new FontCollection(
	    "fontsdotcomfonts",
	    new Font("HelveticaNeueW01-57Cn", FontsDotCom(null)),
	    new Font("HelveticaNeueW01-ThinCn 673383", FontsDotCom(null)),
	    new Font("DIN Next W02 Cond", FontsDotCom(null)),
	    new Font("TradeGothicNextW01-Heav 693241", FontsDotCom(null)),
	    new Font("EurostileNextW01-Regula", FontsDotCom(null)),
	    new Font("FrutigerNeueW01-Regular", FontsDotCom(null))
	  );

	  val cufonFonts = new FontCollection(
	    "cufonfonts",
	    new Font("Open Sans", "Open Sans Condensed", Cufon("/cufon-fonts/Open_Sans_300.font.js")),
	    new Font("Bebas Neue", Cufon("/cufon-fonts/bebas-neue.cufonfonts.js"), letterSpacingFactor = 1),
	    new Font("League Gothic", Cufon("/cufon-fonts/league-gothic.cufonfonts.js"), letterSpacingFactor = 0.5),
	    new Font("DIN Condensed Normal", Cufon("/cufon-fonts/DIN_Condensed_Normal_400.font.js"), letterSpacingFactor = 1),
	    new Font("Enigmatic Regular", Cufon("/cufon-fonts/enigmatic.cufonfonts.js"), letterSpacingFactor = 1),
	    new Font("Gnuolane Free", Cufon("/cufon-fonts/gnuolane.cufonfonts.js"), letterSpacingFactor = 0.5),
	    new Font("Steelfish-Regular", Cufon("/cufon-fonts/steelfish.cufonfonts.js"), letterSpacingFactor = 0.7),
	    new Font("WinterthurCondensed", Cufon("/cufon-fonts/winterthurcondensed.cufonfonts.js"), letterSpacingFactor = 0.5),
	    new Font("Zag Regular", Cufon("/cufon-fonts/zag.cufonfonts.js"), letterSpacingFactor = 0.5),
	    new Font("Source Sans Pro", Cufon("/cufon-fonts/Source_Sans_Pro_400.font.js")),
	    new Font("Amble", Cufon("/cufon-fonts/amble_400.font.js")),
	    new Font("Amble-Light", Cufon("/cufon-fonts/amble-light_300.font.js")),
	    new Font("Amble-Light-Condensed", Cufon("/cufon-fonts/amble-light-condensed_300.font.js")),
	    new Font("Cantarell Regular", Cufon("/cufon-fonts/cantarell.cufonfonts.js")),
	    new Font("CartoGothic Std Book", Cufon("/cufon-fonts/cartogothic-std.cufonfonts.js")),
	    new Font("ExpresswayRg-Regular", Cufon("/cufon-fonts/expressway.cufonfonts.js")),
	    new Font("Helvetica Neue", Cufon("/cufon-fonts/Helvetica_Neue_400-Helvetica_Neue_700-Helvetica_Neue_italic_400-Helvetica_Neue_italic_700.font.js")),
	    new Font("Mentone SemiBold", Cufon("/cufon-fonts/mentone.cufonfonts.js")),
	    new Font("Myriad Pro Regular", Cufon("/cufon-fonts/myriad-pro.cufonfonts.js")),
	    new Font("PT Sans", Cufon("/cufon-fonts/pt-sans.cufonfonts.js")),
	    new Font("Urbano", Cufon("/cufon-fonts/Urbano_400-Urbano_700-Urbano_italic_400-Urbano_italic_700.font.js")),
	    new Font("Urbano Condensed", Cufon("/cufon-fonts/Urbano_Cond_400-Urbano_Cond_700-Urbano_Cond_italic_400-Urbano_Cond_italic_700.font.js")),
	    new Font("Urbano Extra Condensed", Cufon("/cufon-fonts/Urbano_Cond_400-Urbano_Cond_700-Urbano_Cond_italic_400-Urbano_Cond_italic_700.font_2.js")),
	    new Font("XXX", Cufon("/cufon-fonts/Urbano_Extra_Cond_400-Urbano_Extra_Cond_800-Urbano_Extra_Cond_400-Urbano_Extra_Cond_italic_800.font.js")),
	    new Font("XXX", Cufon("/cufon-fonts/Urbano_Light_300-Urbano_Light_300-Urbano_Light_italic_300-Urbano_Light_italic_300.font.js")),
	    new Font("XXX", Cufon("/cufon-fonts/Urbano_Light_400-Urbano_Light_800-Urbano_Light_400-Urbano_Light_italic_800.font.js")),
	    new Font("XXX", Cufon("/cufon-fonts/Urbano_Light_Cond_300-Urbano_Light_Cond_300-Urbano_Light_Cond_italic_300-Urbano_Light_Cond_italic_300.font.js"))
	  );

	    val newGoogleWebFonts = new FontCollection("newGooglewebfonts",
	      new Font("Fenix", GoogleWebFonts(null)), 
	      new Font("Carrois Gothic", GoogleWebFonts(null)),
	      new Font("Carrois Gothic SC", GoogleWebFonts(null)), 
	      new Font("Arbutus Slab", GoogleWebFonts(null)),
	      new Font("Marcellus SC", GoogleWebFonts(null)),
	      new Font("BenchNine", GoogleWebFonts(null)),
	      new Font("ABeeZee", GoogleWebFonts(null)),
	      new Font("Marcellus", GoogleWebFonts(null)),
	      new Font("Titillium Web", GoogleWebFonts(null)),
	      new Font("Archivo Black", GoogleWebFonts(null)),
	      new Font("Archivo Narrow", GoogleWebFonts(null)),
	      new Font("Scada", GoogleWebFonts(null))
	    )

	  val googleWebFonts = new FontCollection(
	    "googlewebfonts",
	    new Font("Allerta Stencil", GoogleWebFonts(null)), //, TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Anonymous Pro", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Buda", "", 300,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Candal", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_HEAVY),
	    new Font("Cantarell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Coda", "", 800,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    //		new Font2("Coda Caption", "", 800,	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_HEAVY),
	    new Font("Cousine", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Didact Gothic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans Mono", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Francois One", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
	    new Font("Inconsolata", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    //		new Font2("Josefin Sans", "Ultra-Light", 100, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    //		new Font2("Josefin Sans", "Book", 300,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    new Font("Josefin Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    //		new Font2("Josefin Sans", "Semi-Bold", 600,		GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    //		new Font2("Josefin Sans", "Bold", 700,			GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    new Font("Jura", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    //		new Font2("Jura", "Medium", 500, 				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    //		new Font2("Jura", "Semi-Bold", 600,				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Lato:light", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT, TAG_WEIGHT_THIN),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Lekton", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Michroma", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Open Sans Condensed", "Book", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
	    //		new Font2("Open Sans Condensed", "Bold", 700,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
	    new Font("Orbitron", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Oswald", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_HEAVY),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Puritan", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    //		new Font2("Raleway", "", 100,		GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Terminal Dosis Light", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Wire One", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_WEIGHT_THIN),
	    //		new Font2("Yanone Kaffeesatz", "Light", 200, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
	    //		new Font2("Yanone Kaffeesatz", "Book", 300, 	GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
	    new Font("Yanone Kaffeesatz", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED)
	  );

	  val normalTextFonts = new FontCollection(
	    "normalSansSerifTextFonts",
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cantarell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Didact Gothic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Open Sans Condensed", "Book", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Puritan", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	  );

	  val goodSerifNormalTextFonts = new FontCollection(
	    "goodSerifNormalTextFonts",
	    new Font("Cambria", ClientOsInstalled())
	  );


	  val goodNormalTextFonts11Px = new FontCollection(
	    "goodNormalTextFonts11Px",
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Lucida Sans Unicode", ClientOsInstalled()),
	    new Font("Arial", ClientOsInstalled())
	  );

	  val goodNormalTextFonts12Px = new FontCollection(
	    "goodNormalTextFonts12Px",
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Lucida Sans Unicode", ClientOsInstalled()),
	    new Font("Arial", ClientOsInstalled())
	  );

	  val goodNormalTextFonts13Px = new FontCollection(
	    "goodNormalTextFonts13Px",
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ratio", CssFontFace(null)),
	    new Font("Arial", ClientOsInstalled())
	  );


	  val goodNormalTextFonts14Px = new FontCollection(
	    "goodNormalTextFonts14Px",
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Consolas", ClientOsInstalled()),
	    new Font("Georgia", ClientOsInstalled()),
	    new Font("Constantia", ClientOsInstalled()),
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Cantarell", 				GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cuprum", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Nunito", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ratio", CssFontFace(null)),
	    new Font("Arial", ClientOsInstalled())
	  );

	  val goodNormalTextFonts15Px = new FontCollection(
	    "goodNormalTextFonts15Px",
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Play", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_GEOMETRIC_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Nobile", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ratio", CssFontFace(null)),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Arial", ClientOsInstalled())
	  );

	  val goodNormalTextFonts16Px = new FontCollection(
	    "goodNormalTextFonts16Px",
	    new Font("Calibri", ClientOsInstalled()),
	    new Font("Segoe UI", ClientOsInstalled()),
	    new Font("PT Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Narrow", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED),
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("Lato", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Mako", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Metrophobic", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Arimo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Muli", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("News Cycle", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Microsoft Sans Serif", ClientOsInstalled()),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("PT Sans Caption", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Abel", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Pontano Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Oxygen", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Shanti", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Quattrocento Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ubuntu", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Varela", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Droid Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Cabin", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    new Font("Molengo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT),
	    new Font("Ratio", CssFontFace(null)),
	    new Font("Corbel", ClientOsInstalled()),
	    new Font("Candara", ClientOsInstalled()),
	    new Font("Arial", ClientOsInstalled())
	  );


	  val googleWebFontsSerifOrSlabSerif = new FontCollection(
	    "googlewebfontsseriforslabserif",
	    new Font("Arvo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Bentham", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Brawler", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Cardo", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Copse", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Crimson Text", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Droid Serif", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("EB Garamond", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Goudy Bookletter 1911", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("IM Fell", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Josefin Slab", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Judson", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Kameron", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Kreon", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Lora", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Merriweather", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Neuton", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("OFL Sorts Mill Goudy TT", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Old Standard TT", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Podkova", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("PT Serif", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Playfair Display", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Quattrocento", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Rokkitt", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SLAB_SERIF_FONT),
	    new Font("Tinos", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SERIF_FONT),
	    new Font("Vollkorn", GoogleWebFonts(null)) // TAG_CLASSIFICATION_SERIF_FONT)
	  );

	  val cssFontFaceFonts = new FontCollection(
	    "cssFontFaceFonts",
	    new Font("elena-web-basic", CssFontFace(null)),
	    new Font("urbano", CssFontFace("urbano_400_normal.css")),
	    new Font("sanchez", CssFontFace("sanchez_400_normal.css")),
	    new Font("atrament-web", CssFontFace(null)),
	    new Font("atrament-web_light", CssFontFace(null)),
	    new Font("etica", CssFontFace(null)),
	    new Font("nudista-web", CssFontFace(null)),
	    new Font("obliqua", CssFontFace(null)),
	    new Font("ronnia-condensed", CssFontFace(null)),
	    new Font("alternate-gothic-no-3-d", CssFontFace(null)),
	    new Font("franklin-gothic-comp-urw", CssFontFace(null)),
	    new Font("franklin-gothic-ext-comp-urw", CssFontFace(null)),
	    new Font("ratio-display", CssFontFace(null)),
	    new Font("runda", CssFontFace(null)),
	    new Font("ronnia", CssFontFace(null)),
	    new Font("prenton-condensed", CssFontFace(null)),
	    new Font("comenia-sans-web", CssFontFace(null)),
	    new Font("katarine-web", CssFontFace(null)),
	    new Font("adelle", CssFontFace(null)),
	    new Font("republic-web-condensed", CssFontFace(null)),
	    new Font("crete-rounded-web", CssFontFace(null)),
	    new Font("league-gothic", CssFontFace(null)),
	    new Font("bebas-neue", CssFontFace(null)),
	    new Font("vinyl", CssFontFace(null)),
	    new Font("p22-underground-pc", CssFontFace(null)),
	    new Font("gnuolane", CssFontFace(null)),
	    new Font("allumi-std-extended", CssFontFace(null)),
	    new Font("etica-display", CssFontFace(null)),
	    new Font("sommet", CssFontFace(null)),
	    new Font("t26-carbon", CssFontFace(null)),
	    new Font("purista-web", CssFontFace(null)),
	    new Font("sirba-web", CssFontFace(null)),
	    new Font("apolline", CssFontFace(null)),
	    new Font("lemonde-journal", CssFontFace(null))
	  );

	  val typekitGoodWindowsRenderingSansSerifs = new FontCollection(
	    "typekitgoodwindowsrenderingsansserifs",
	    new Font("Source Sans Pro", GoogleWebFonts(null)),
	    new Font("adelle-sans", CssFontFace(null)),
	    new Font("etica", CssFontFace(null)),
	    new Font("nudista-web", CssFontFace(null)),
	    new Font("obliqua", CssFontFace(null)),
	    new Font("runda", CssFontFace(null)),
	    new Font("ronnia", CssFontFace(null)),
	    new Font("ronnia-condensed", CssFontFace(null)),
	    new Font("prenton-condensed", CssFontFace(null)),
	    new Font("parisine-std", CssFontFace(null)),
	    new Font("comenia-sans-web", CssFontFace(null)),
	    new Font("katarine-web", CssFontFace(null)),
	    new Font("calluna-sans", CssFontFace(null)),
	    new Font("ratio-display", CssFontFace(null)),
	    new Font("gnuolane", CssFontFace(null)),

	    new Font("quara-web", CssFontFace(null)),
	    new Font("tilden-sans-light", CssFontFace(null)),
	    new Font("allumi-std", CssFontFace(null)),
	    new Font("allumi-std-extended", CssFontFace(null)),
	    new Font("cronos-pro-display", CssFontFace(null)),


	    new Font("museo-sans-rounded", CssFontFace(null)),

	    new Font("franklin-gothic-comp-urw", CssFontFace(null)),
	    new Font("franklin-gothic-ext-comp-urw", CssFontFace(null)),
	    new Font("alternate-gothic-no-1-d", CssFontFace(null)),
	    new Font("alternate-gothic-no-2-d", CssFontFace(null)),
	    new Font("alternate-gothic-no-3-d", CssFontFace(null)),
	    new Font("league-gothic", CssFontFace(null)),
	    new Font("bebas-neue", CssFontFace(null)),


	    new Font("etica-display", CssFontFace(null)),
	    new Font("sommet", CssFontFace(null)),
	    new Font("t26-carbon", CssFontFace(null)),

	    new Font("p22-underground-pc", CssFontFace(null)),
	    new Font("soleil", CssFontFace(null)),

	    new Font("tablet-gothic-wide", CssFontFace(null)),
	    new Font("tablet-gothic", CssFontFace(null)),
	    new Font("tablet-gothic-narrow", CssFontFace(null)),
	    new Font("tablet-gothic-semi-condensed", CssFontFace(null)),
	    new Font("tablet-gothic-condensed", CssFontFace(null)),
	    new Font("tablet-gothic-compressed", CssFontFace(null)),

	    new Font("atrament-web", CssFontFace(null)),
	    new Font("purista-web", CssFontFace(null)),
	    new Font("vinyl", CssFontFace(null))


	  );

	  val typekitBestRenderingSansSerifs20Px = new FontCollection(
	    "typekitBestRenderingSansSerifs20Px",

	    new Font("adelle-sans", CssFontFace(null)),
	    new Font("museo-sans-rounded", CssFontFace(null)),
	    new Font("tablet-gothic-condensed", CssFontFace(null)),
	    new Font("alternate-gothic-no-3-d", CssFontFace(null)),
	    new Font("soleil", CssFontFace(null)),
	    new Font("purista-web", CssFontFace(null)),
	    new Font("etica", CssFontFace(null)),
	    new Font("nudista-web", CssFontFace(null)),
	    new Font("obliqua", CssFontFace(null)),
	    new Font("runda", CssFontFace(null)),
	    new Font("ronnia", CssFontFace(null)),
	    new Font("ronnia-condensed", CssFontFace(null)),
	    new Font("parisine-std", CssFontFace(null)),
	    new Font("comenia-sans-web", CssFontFace(null)),
	    new Font("katarine-web", CssFontFace(null)),
	    new Font("calluna-sans", CssFontFace(null)),

	    new Font("quara-web", CssFontFace(null)),
	    new Font("allumi-std", CssFontFace(null)),
	    new Font("allumi-std-extended", CssFontFace(null)),
	    new Font("cronos-pro-display", CssFontFace(null)),


	    new Font("franklin-gothic-comp-urw", CssFontFace(null)),


	    new Font("bebas-neue", CssFontFace(null)),

	    new Font("sommet", CssFontFace(null)),
	    new Font("t26-carbon", CssFontFace(null)),


	    new Font("tablet-gothic-wide", CssFontFace(null)),
	    new Font("tablet-gothic", CssFontFace(null)),
	    new Font("tablet-gothic-semi-condensed", CssFontFace(null)),

	    new Font("tablet-gothic-compressed", CssFontFace(null))


	  );

	  val typekitGoodWindowsRenderingSerifs = new FontCollection(
	    "typekitgoodwindowsrenderingserifs",
	    new Font("adelle", CssFontFace(null)),
	    new Font("republic-web-condensed", CssFontFace(null)),
	    new Font("crete-rounded-web", CssFontFace(null)),
	    new Font("sirba-web", CssFontFace(null)),
	    new Font("apolline", CssFontFace(null)),
	    new Font("bree-serif", CssFontFace(null)),
	    new Font("lemonde-journal", CssFontFace(null))
	  );


	  val dinAlternatives = new FontCollection(
	    "dinAlternatives",
	    new Font("DIN Next W02 Cond", FontsDotCom(null)),
	    new Font("atrament-web", CssFontFace(null)),
	    new Font("nudista-web", CssFontFace(null)),
	    new Font("purista-web", CssFontFace(null))
	  );

	  val helveticaAlternatives = new FontCollection(
	    "helveticaAlternatives",
	    new Font("HelveticaNeueW01-57Cn", FontsDotCom(null)),
	    new Font("Open Sans", GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_CLASSIFICATION_REALIST_FONT),
	    //		new Font2("Open Sans Condensed", "Light", 300,GoogleWebFonts(null)), // TAG_CLASSIFICATION_SANS_SERIF_FONT, TAG_STRECH_CONDENSED, TAG_WEIGHT_THIN),
	    new Font("etica", CssFontFace(null)),
	    new Font("nudista-web", CssFontFace(null)),
	    new Font("ratio-display", CssFontFace(null)),
	    new Font("runda", CssFontFace(null)),
	    new Font("ronnia", CssFontFace(null)),
	    new Font("comenia-sans-web", CssFontFace(null)),
	    new Font("katarine-web", CssFontFace(null))
	  );

	  val geometricSansSerif = new FontCollection(
	    "Geometric Sans Serifs",
	    new Font("MuseoSans_500-webfont", "Museo Sans 500", FontFace("/font-face-kit/museo-sans-fontfacekit")),
	    new Font("museo-sans-rounded", CssFontFace(null)),
		new Font("soleil", CssFontFace(null)),
		new Font("Questrial", GoogleWebFonts(null)),
		new Font("SofiaProLight-webfont", "Sofia Pro Light", FontFace("/font-face-kit/sofia-pro-fontfacekit")),
		new Font("Montserrat", GoogleWebFonts(null))
	  );

	val alternateGothicAlternatives = new FontCollection(
	    "Alternate Gothic Alternatives", 
	    new Font("franklin-gothic-comp-urw", CssFontFace(null)),
	    new Font("franklin-gothic-ext-comp-urw", CssFontFace(null)),
	    new Font("alternate-gothic-no-1-d", CssFontFace(null)),
	    new Font("alternate-gothic-no-2-d", CssFontFace(null)),
	    new Font("alternate-gothic-no-3-d", CssFontFace(null)),
	    new Font("league-gothic", CssFontFace(null)),
	    new Font("bebas-neue", CssFontFace(null)),
	    new Font("Oswald-Regular-webfont", "Oswald", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Oswald-Light-webfont", "Oswald Light", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("Oswald-Bold-webfont", "Oswald Bold", FontFace("/font-face-kit/oswald-fontfacekit"), letterSpacingFactor = 1),
	    new Font("DIN Next W02 Cond", FontsDotCom(null))
	)



	  
	  val fontCollectionDefaultText: FontCollection = standardFonts
	  val fontCollectionNormalText: FontCollection = goodNormalTextFonts14Px
	  val fontCollectionHeadings: FontCollection = newGoogleWebFonts
	  val fontCollectionSmallText: FontCollection = standardFonts
	  val fontCollectionLargeText: FontCollection = standardFonts
	  val fontCollectionMenu: FontCollection = standardFonts
	  val fontCollectionBanner: FontCollection = standardFonts
	  val fontCollectionButtons: FontCollection = standardFonts
	  val fontCollectionLogo: FontCollection = standardFonts
	}
}#